language: ruby
sudo: false
cache: bundler

services:
  - mongodb
rvm:
  - 2.2
  - 2.1
  - 1.9.3
  - jruby-19mode
  - rbx-2

gemfile:
  - gemfiles/active_model_4.1.gemfile
  - gemfiles/active_model_4.2.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
